translationsite/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("sign-up", views.register, name="signup"),
    path("login", views.login, name="login"),
]

translationsite/app/urls.py
from django.urls import path, include
from . import views
from django.urls import include
from .forms import EmailChangeForm

app_name = "app"
urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path("post_job", views.post_job, name="post_job"),
    path(
        "profile/<int:user_id>/password_change",
        views.change_password,
        name="new_password",
    ),
    path("profile/<int:user_id>/email_change", views.email_change, name="new_email"),
    path("jobs", views.jobs, name="jobs"),
    path("jobs/job_bid/<int:job_id>", views.job_bid, name="jobs_bid"),
    path("jobs/<int:job_id>", views.message_user, name="message_user"),
    path(
        "profile/<int:user_id>/<int:job_id>",
        views.complete_job,
        name="complete_job",
    ),
    path("dashboard/accept/<int:bid_id>", views.accept_job, name="accept_job"),
    path("dashboard/job_status/<int:job_id>", views.job_status, name="job_status"),
    path(
        "dashboard/dispute/<int:job_id>",
        views.dispute_job,
        name="dispute_job",
    ),
    path("profile/password_change", views.change_password, name="new_password"),
    path("profile/email_change", views.email_change, name="new_email"),
    path(
        "dashboard/job_review/<int:job_id>/rate/<int:new_rating>",
        views.job_rating,
        name="job_rating",
    ),
    path(
        "dashboard/translation/<int:job_id>",
        views.view_translation,
        name="view_translation",
    ),
    path("dashboard/job_review/<int:job_id>", views.job_review, name="job_review"),
]

translationsite/translationsite/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("app.urls")),
    path("", views.home, name="home_path"),
]

translationsite/app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html>

  <head>
    <title>Translation app</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'app/css/base.css' %}">
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid  p-2 ms-4 me-4">
            <a class="navbar-brand" href="{% url 'home_path' %}"><img class="logo" src="../../static/app/images/p-logo.webp"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
            
              {% if user.is_authenticated %}
                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    
                  <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'app:jobs' %}">Jobs</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:post_job' %}">Post a job</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'app:profile' user.id %}">Profile</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}"> Signout</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'app:dashboard' %}"> My jobs | {{user.username}}</a>
                    </li>
              {% else %}
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Register</a>
                  </li>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>


    <div class="content container">
      <div class="row">
        <div class="col-md-12">
            <div class="p-3 mb-4 rounded-3  jumbotron-container">
                <div class="container-fluid py-4">
                    <h1 class="display-5 fw-bold">Translate-o-Rama</h1>
                    <p class="col-md-8 fs-4">Web application that enables users to hire translators to translate their texts quickly and conveniently.</p>
                </div>
            </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>


    

  </body>
</html>

translationsite/app/templates/app/complete_job.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<h1 class="text-center mb-5 mt-3">Translate job</h1>
<div class="content-section mt-5 mb-5 p-2 ">
	<div class="container w-50 mb-5 justify-content-center">
		<div class="ms-5">
			<p><b>Title:</b> {{job.title}}</p>
			<p><b>Description:</b> {{job.description}}</p>
			<p><b>Source language:</b> {{job.source_language}}</p>   
			<p><b>Text to translate:</b> {{job.text}}</p>   
			<p><b>Target language:</b> {{job.target_language}}</p>   
		</div>
	</div>
	<form action="{% url 'app:complete_job' user.id job.id %}" method="POST">
		<div class="form-group">
			{% csrf_token %}
			{% include 'includes/job_form.html' with form=form %}
	
			<div class="row mt-4 text-center mb-5">
				<div clss="col-md-8 ms-2">
					<button class="btn custom-btn" type="submit">Submit</button>
				</div>
			</div>
		</div>
    </form>
</div>
{% endblock content %}

translationsite/app/templates/app/dashboard.html
{% extends 'app/base.html' %}
{% block content %}

  <style>
    .rating-list li {
      float: right;
      color: #ddd;
      padding: 10px 5px;
    }

    .rating-list li:hover,
    .rating-list li:hover ~ li {
      color: orange;
    }

    .rating-list {
      display: inline-block;
      list-style: none;
    }
    .checked {
        color: orange;
    }
  </style>


  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center mt-3 mb-5">Dashboard</h1>
    </div>
  </div>
  
  <h5 class="mb-3"><b>Username:</b> {{ user.username }}</h5>
  <h5 class="mb-3"><b>E-mail:</b> {{ user.email }}</h5>
  <h5 class="mb-3"><b>Token balance:</b> {{ user.userprofile.token_balance }} token(s)</h5>

  {% if user.userprofile.is_translator %}
        <h5 class="mb-3"><b>Avg rating:</b>
            <span class="bi bi-star-fill {% if rating > 0 %} checked {% endif %}"></span>
            <span class="bi bi-star-fill {% if rating > 1 %} checked {% endif %}"></span>
            <span class="bi bi-star-fill {% if rating > 2 %} checked {% endif %}"></span>
            <span class="bi bi-star-fill {% if rating > 3 %} checked {% endif %}" ></span>
            <span class="bi bi-star-fill {% if rating > 4 %} checked {% endif %}"></span>
        </h5>
    {% endif %}


  <h2 class="text-center mt-5">Jobs</h2>

  <div class="mb-5">
    {% for job in jobs %}
      {% include 'includes/job_card.html' with job=job %}
      <a href="{% url 'app:job_status' job.id %}" class="btn custom-btn col-2">View status</a>
      
      {% if job.is_assigned %}
        <span class="ms-5">Assigned to <a href="{% url 'app:profile' job.assigned_to.bid_user.id %}">{{ job.assigned_to.bid_user.username }}</a></span>
        {% if job.is_completed %}
          <a href="{% url 'app:job_review' job.id %}" class="btn custom-btn mx-2">Review</a>
          
            {% if job.dispute.status == "Closed" %}
              <span class="ms-5">Dispute closed</span>
            {% else %}
              <a href="{% url 'app:dispute_job' job.id %}" class="btn custom-btn ms-5">Dispute</a>
            {% endif %}
          
          <a href="{% url 'app:view_translation' job.id %}" class="btn custom-btn mx-2">View translation</a>
        {% endif %}

      {% else %}

        {% for bid in bids %}
          {% if bid.job == job %}
            <div class="row my-3">
              <h5 class="col-3 d-block"><a href="{% url 'app:profile' bid.bid_user.id %}">{{ bid.bid_user }}</a>: {{ bid.bid }}</h5>
              <form action="{% url 'app:accept_job' bid.id %}" class="col-3" method="post">
                {% csrf_token %}
                <button type="submit" class="btn custom-btn col-3">Accept</button>
              </form>
            </div>
          {% endif %} 
        {% endfor %}
      {% endif %}
      {% empty %}
      <div class="row">
        No jobs posted.
      </div>
    {% endfor %}
  </div>
  
  <div class="design-color pb-5 card  mb-5">
    <h2 class="text-center mt-5 mb-5">Messages</h2>
    
    <div class="mb-4 w-75 mx-auto bg-light">
      {% for message in messages %}
      
          {% include 'includes/message_card.html' with message=message user=user%}
       
      {% empty %}
        <div class="row">
          No messages.
        </div>
      {% endfor %}
    </div>
  </div>


  {% if user.userprofile.is_translator %}
    <h2 class="text-center mt-5 mb-4">Submitted bids</h2>
    {% for bid in translator_bids %}
      {% include 'includes/bid_form.html' with job_bid=bid %}
    {% endfor %}

    <h2 class="text-center mt-5 mb-4">Assigned jobs</h2>
    {% for a_job in assigned_jobs %}
      {% include 'includes/job_card.html' with job=a_job %}
      <form action="{% url 'app:complete_job' user.id a_job.id %}">
        {% csrf_token %}
        <div class="row mt-4 text-center mb-5">
            <div clss="col-md-8 ms-2">
                <input type="submit" value="Complete" class="custom-btn btn px-4 py-2">
            </div>
        </div>
    </form>
    {% endfor %}

    <!--Jobs that he ended-->
    <h2 class="text-center mt-5 mb-4">Completed jobs</h2>
    {% for c_job in completed_jobs %}
      {% include 'includes/job_card.html' with job=c_job %}
    {% endfor %}

  {% endif %}

{% endblock content %}

translationsite/app/templates/app/dispute_job.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<h1 class="text-center mb-5 mt-3">Dispute job</h1>
<div class="content-section mt-5 mb-5 p-2 ">
	<div class="container w-50 mb-5 justify-content-center">
		<div class="ms-5">
			<p><b>Title:</b> {{job.title}}</p>
			<p><b>Description:</b> {{job.description}}</p>
            <p><b>Source language:</b> {{job.source_language}}</p>      
			<p><b>Text for translation:</b> {{job.text}}</p>
            <p><b>Posted by:</b> {{job.user}}</p> 
            <hr>     
            <p><b>Target language:</b> {{job.target_language}}</p>   
            <p><b>Translation:</b> {{job.translation}}</p> 
            <p><b>Completed by:</b> {{job.translator}}</p>     
		</div>

	</div>
	<form action="{% url 'app:dispute_job' job.id %}" method="POST">
		{% csrf_token %}
		{% include 'includes/job_form.html' with form=form %}
   
		<div class="row mt-4 text-center mb-5">
            <div clss="col-md-8 ms-2">
				<button class="btn custom-btn" type="submit">
					Submit
				</button>
			</div>
		</div>
    </form>
</div>
{% endblock content %}

translationsite/app/templates/app/email_change.html
{% load widget_tweaks %}
    <div class="content-section mt-5 mb-5 p-2">
        <h3>Change Email</h3><hr>
        <p class="h6 mb-3">Please enter your new email.</p>
        <form action="{% url 'app:new_email' user.id %}" method="POST">
            {% csrf_token %}
            {{ email_form }}
            <button class="btn custom-btn ms-3" type="submit">Reset email</button>
        </form>
    </div>

translationsite/app/templates/app/home.html
{% extends 'app/base.html' %}
{% block content %}
        
        
        <h1 class="text-center mt-3">Translators</h3>
        {% for translator in translators %}
                {% include 'includes/user_card.html' with user=translator %}
                {% empty %}
                <div class="row">
                No translators.
                </div>
        {% endfor %}
        
        <h1 class="text-center mt-5">Available jobs</h3>

        <div class="row mx-auto mt-5 pt-5 pb-3 bg-light">
                       
            <form method="GET" action="{% url 'home_path' %}">
                 
                <div class="form-row w-50 mx-auto">
                    <div class="form-group col-12">
                        <div class="input-group">
                            <input class="form-control py-2 border-right-0 border" type="search" name="target_language" placeholder="Language..." />
                           
                        </div>
                    </div>        
                </div>
                
                <select class="form-select w-50 mx-auto mt-3"  name="job_field" aria-label="Default select example">
                    <option value="">-</option>
                    <option value="Art">Art</option>
                    <option value="Business">Business</option>
                    <option value="Computers">Computers</option>
                    <option value="Education">Education</option>
                    <option value="Engineering">Engineering</option>
                    <option value="Finance">Finance</option>
                    <option value="Law">Law</option>
                    <option value="Literature">Literature</option>
                    <option value="Medicine">Medicine</option>
                    <option value="Science">Science</option>
                    <option value="Social Sciences">Social Sciences</option>
                    <option value="Technology">Technology</option>
                </select>      
               
                   
                <div class="mx-auto text-center mt-3">
                    <button class="btn custom-btn " type="submit">Search</button>
                </div>
                        
        </form>
        </div>
        {% for job in available_jobs %}
                
                {% include 'includes/unassigned_jobs.html' with job=job user=user %}
                {% empty %}
                <div class="row">
                        No jobs posted.
                </div>
        {% endfor %}
{% endblock content %}

translationsite/app/templates/app/job_status.html
{% extends 'app/base.html' %}
{% block content %}
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
      <meta charset="UTF-8">
      <title>Rating</title>
  </head>
  <body>
    <style>
      .rating-list li {
        float: right;
        color: #ddd;
        padding: 10px 5px;
      }

      .rating-list a,
      .rating-list li:hover,
      .rating-list li:hover ~ li {
        color: orange;
      }

      .rating-list {
        display: inline-block;
        list-style: none;
      }
      .checked {
          color: orange;
      }
    </style>
    <div class="mx-2">
      <h4>{{ job.title }}
        {% if job.is_assigned %}
          {% if job.is_completed %}
            <div class="badge bg-success">Completed</div>
          {% else %}
            <div class="badge bg-primary">Assigned</div>
          {% endif %}
        {% else %}
          <div class="badge bg-secondary">Unassigned</div>
        {% endif %}
      </h4>
      <div class="mb-2 text-muted">Budget: {{ job.budget }} token(s)</div>
      <div class="">{{ job.description }}</div>
      
      <a href="{% url 'app:dashboard' %}" class="btn btn-secondary col-2 mt-4">Back</a>
    </div>
  </body>
{% endblock content %}

translationsite/app/templates/app/jobs.html
{% extends 'app/base.html' %}

{% block content %}
    <h1 class="text-center mb-5 mt-3">Jobs</h1>
    <div class="mb-4">
        {% for job in jobs %}
          {% include 'includes/unassigned_jobs.html' with job=job %}
        {% empty %}
          <div class="row">
            No jobs posted.
          </div>
        {% endfor %}
      </div>
   
{% endblock content %}

translationsite/app/templates/app/message_page.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<h1 class="text-center mb-5 mt-3">Message</h1>
<div class="content-section mt-5 mb-5 p-2 ">
	<div class="container w-50 mb-5 justify-content-center">
		<div class="ms-5">
			<p><b>From:</b> {{user.username}}</p>
			<p><b>To:</b> {{job.user.username}}</p>   
			<p><b>For job:</b> {{job}}</p>   
		</div>
	</div>
	<form action="{% url 'app:message_user' job.id %}" method="POST">
		{% csrf_token %}
		{% include 'includes/job_form.html' with form=form %}

		<div class="row mt-4 text-center mb-5">
            <div clss="col-md-8 ms-2">
				<button class="btn custom-btn" type="submit">Send message</button>
			</div>
		</div>
	</form>

</div>
{% endblock content %}

translationsite/app/templates/app/password_change.html
{% load widget_tweaks %}
    <div class="content-section mt-5 mb-5 p-2 ">
        <h3>Change Password</h3><hr>
        <p class="h6 mb-3">Please enter your new password.</p>
        <form action="{% url 'app:new_password' user.id %}" method="POST">
            {% csrf_token %}
            {{ password_form }}
            <button class="btn custom-btn ms-3" type="submit">Reset password</button>
        </form>
    </div>

translationsite/app/templates/app/post_job.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<h1 class="text-center mb-5 mt-3">Post Job</h1>
    <form action="{% url 'app:post_job' %}" method="post">
        <div class="form-group">
        {% csrf_token %}
        {% include 'includes/job_form.html' with form=form %}

        <div class="row mt-4 text-center mb-5">
            <div clss="col-md-8 ms-2">
                <input type="submit" value="Post" class="custom-btn btn px-4 py-2">
            </div>
        </div>
        </div>
    </form>
{% endblock content %}

translationsite/app/templates/app/profile.html
{% extends 'app/base.html' %}
{% block content %}

    <style>
        .rating-list li {
          float: right;
          color: #ddd;
          padding: 10px 5px;
        }

        .rating-list li:hover,
        .rating-list li:hover ~ li {
          color: orange;
        }

        .rating-list {
          display: inline-block;
          list-style: none;
        }
        .checked {
            color: orange;
        }
    </style>

    
    <h1 class="text-center mb-5 mt-3">User profile</h1>

    <h5 class="mb-3"><b>Username:</b>{{ user_from_jobs.username }}</h5>

    <h5 class="mb-3"><b>Email address:</b> {{ user_from_jobs.email }}</h5>

    {% if user_from_jobs.userprofile.is_translator %}
        <h5 class="mb-3"><b>Avg rating:</b>
            <span class="bi bi-star-fill {% if rating > 0 %} checked {% endif %}"></span>
            <span class="bi bi-star-fill {% if rating > 1 %} checked {% endif %}"></span>
            <span class="bi bi-star-fill {% if rating > 2 %} checked {% endif %}"></span>
            <span class="bi bi-star-fill {% if rating > 3 %} checked {% endif %}" ></span>
            <span class="bi bi-star-fill {% if rating > 4 %} checked {% endif %}"></span>
        </h5>
    {% endif %}

    <h5 class="mb-3"><b>Accepted jobs:</b></h5>
    {% for accepted_job in accepted_jobs %}
        {% include 'includes/job_card.html' with job=accepted_job %}
        {% empty %}
        <p >
          No jobs posted.
        </p>
    {% endfor %}

    <h5 class="mb-3"><b>Completed jobs:</b></h5>
    {% for completed_job in completed_jobs %}
        {% include 'includes/job_card.html' with job=completed_job %}
        {% empty %}
        <p >
          No jobs posted.
        </p>
    {% endfor %}
    
    {% if user.id == user_from_jobs.id %}
    <div class="bg-light py-1 my-3">
        <div class="form-group">
            {% block email_new %}
                {% include 'app/email_change.html' with form=email_form %}
            {% endblock%}
        </div>
        <div class="form-group">
            {% block password_new %}
                {% include 'app/password_change.html' with form=password_form %}
            {% endblock%}
        </div>
    </div>
    {% endif %}

    {% if user.userprofile.is_translator %}
        {% if user_from_jobs == user %}
            <h2 class="text-center mt-5 mb-4">Submitted bids</h2>
            {% for bid in translator_bids %}
                {% include 'includes/bid_form.html' with job_bid=bid %}
            {% endfor %}

            <h2 class="text-center mt-5 mb-4">Assigned jobs</h2>
            {% for job in translator_assigned_jobs %}
                {% include 'includes/job_card.html' with job=job %}
                <!--za complete btn-->
                {% if user.id == job.translator.id %}
                <form action="{% url 'app:complete_job' user.id job.id %}">
                    {% csrf_token %}
                    <div class="row mt-4 text-center mb-5">
                        <div clss="col-md-8 ms-2">
                            <input type="submit" value="Complete" class="custom-btn btn px-4 py-2">
                        </div>
                    </div>
                </form>
                {% endif %}
            {% endfor %}
            
            <!--Jobs that he ended-->
            <h2 class="text-center mt-5 mb-4">Completed jobs</h2>
            {% for c_job in translator_completed_jobs %}
                {% include 'includes/job_card.html' with job=c_job %}
            {% endfor %}
        {% endif %}
    {% endif %}

{% endblock %}

translationsite/app/templates/app/review.html
{% extends 'app/base.html' %}
{% block content %}
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
      <meta charset="UTF-8">
      <title>Rating</title>
  </head>
  <body>
    <style>
      .rating-list li {
        float: right;
        color: #ddd;
        padding: 10px 5px;
      }

      .rating-list a,
      .rating-list li:hover,
      .rating-list li:hover ~ li {
        color: orange;
      }

      .rating-list {
        display: inline-block;
        list-style: none;
      }
      .checked {
          color: orange;
      }
    </style>
    <div class="mx-auto  mt-5">
      <h4>{{ job.title }}</h4>
      <div class="mb-2 text-muted">Budget: {{ job.budget }} token(s)</div>
      <div class="">{{ job.description }}</div>

      <div class="row mt-2 mb-2">
        <div class="col-2 mt-2">
            <ul class="btn btn-light list-inline rating-list">
            <a href="{% url 'app:job_rating' job.id 5 %}"><li>
                <i class="bi bi-star-fill {% if rating > 4 %} checked {% endif %}" title="Rate 5"></i></li></a>
            <a href="{% url 'app:job_rating' job.id 4 %}"><li>
                <i class="bi bi-star-fill {% if rating > 3 %} checked {% endif %}" title="Rate 4"></i></li></a>
            <a href="{% url 'app:job_rating' job.id 3 %}"><li>
                <i class="bi bi-star-fill {% if rating > 2 %} checked {% endif %}" title="Rate 3"></i></li></a>
            <a href="{% url 'app:job_rating' job.id 2 %}"><li>
                <i class="bi bi-star-fill {% if rating > 1 %} checked {% endif %}" title="Rate 2"></i></li></a>
            <a href="{% url 'app:job_rating' job.id 1 %}"><li>
                <i class="bi bi-star-fill {% if rating > 0 %} checked {% endif %}" title="Rate 1"></i></li></a>
            </ul>
        </div>
        <div class="col-2"> 
            <a href="{% url 'app:dashboard' %}" class="btn btn-secondary col-6 mt-4">Back</a>
        </div>
        
      </div>
    </div>
  </body>
{% endblock content %}

translationsite/app/templates/app/view_translation.html
{% extends 'app/base.html' %}
{% block content %}
  <div class="m-4">
    <h3 class="text-center"><b>{{ job.title }}</b></h3>
    <h4 class="my-2">Description: {{ job.description }}</h4>
    <div class="row mt-5">
      <h5 class="col-6"><b>Text</b> ({{ job.source_language }})</h5>
      <h5 class="col-6"><b>Translation</b> ({{ job.target_language }})</h5>
    </div>
    <div class="row mt-2 mb-2">
      <h5 class="col-6">{{ job.text }}</h5>
      <h5 class="col-6">{{ job.translation }}</h5>
    </div>
    <a href="{% url 'app:dashboard' %}" class="btn btn-secondary col-2 mt-5">Back</a>
  </div>
{% endblock %}