translationsite/app/urls.py
from django.urls import path, include
from . import views
from django.urls import include
from .forms import EmailChangeForm

app_name = "app"
urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path("post_job", views.post_job, name="post_job"),
    path(
        "profile/<int:user_id>/password_change",
        views.change_password,
        name="new_password",
    ),
    path("profile/<int:user_id>/email_change", views.email_change, name="new_email"),
    path("jobs", views.jobs, name="jobs"),
    path("jobs/job_bid/<int:job_id>", views.job_bid, name="jobs_bid"),
    path("jobs/<int:job_id>", views.message_user, name="message_user"),
    path(
        "profile/<int:user_id>/<int:job_id>",
        views.complete_job,
        name="complete_job",
    ),
    path("dashboard/accept/<int:bid_id>", views.accept_job, name="accept_job"),
    path("dashboard/job_status/<int:job_id>", views.job_status, name="job_status"),
    path(
        "dashboard/dispute/<int:job_id>",
        views.dispute_job,
        name="dispute_job",
    ),
    path("profile/password_change", views.change_password, name="new_password"),
    path("profile/email_change", views.email_change, name="new_email"),
    path(
        "dashboard/job_review/<int:job_id>/rate/<int:new_rating>",
        views.job_rating,
        name="job_rating",
    ),
    path(
        "dashboard/translation/<int:job_id>",
        views.view_translation,
        name="view_translation",
    ),
    path("dashboard/job_review/<int:job_id>", views.job_review, name="job_review"),
]

translationsite/translationsite/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("app.urls")),
    path("", views.home, name="home_path"),
]

translationsite/app/templates/includes/bid_form.html
<div class="card my-4 shadow-sm p-3 mb-5">
    <div class="card-body m-2">
      <h4 class="card-title">{{ job_bid.job.title }}</h4>
      <div class="card-text">{{ job_bid.job.description }}</div>
      <div class="card-subtitle mb-2 text-muted">Budget: {{ job_bid.bid }} token(s)</div>
    </div>
  </div>

translationsite/app/templates/includes/bs_form.html
{% load widget_tweaks %}

 {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
        </div>
    {% endif %}

    {% for field in form.visible_fields %}
        <div class=" row g-2 align-items-center">
            <div class="col-6 mx-auto">
                <label class="col-form-label mt-2">{{ field.label_tag }}</label>

                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        </div>
    {% endfor %}

translationsite/app/templates/includes/job_card.html
<div class="card my-4 shadow-sm p-3 mb-5  rounded">
  <div class="card-body m-2">
    <div class="row">
      <h4 class="card-title">{{ job.title }}</h4>
    </div>
    <div class="card-subtitle mb-2 text-muted">Budget: {{ job.budget }} token(s)</div>
    <div class="card-text mb-2">{{ job.description }}</div>
  </div>
</div>

translationsite/app/templates/includes/job_form.html
{% load widget_tweaks %}

 {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
        </div>
    {% endif %}

    {% for field in form.visible_fields %}
        
        <div class='form-group mt-3 mb-5 d-flex justify-content-center'>
            <label class='control-label col-md-1 col-md-offset-2'>{{ field.label_tag }}</label>
            <div class='col-md-6' >


                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" rows="1" cols="1" type='text'%}
                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        </div>
        
    {% endfor %}

translationsite/app/templates/includes/message_card.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/css/message_card.css' %}">
</head>

<div id="container">
    <main>
  
    
      <ul id="chat">
        <li class="{% if user == message.from_user %} me {% else %} you {% endif %}">
          <div class="entete">
            <span class=" status {% if user == message.from_user %} blue {% else %} green {% endif %}"></span>
            <h2>{% if user == message.from_user %} 
                    {{ message.from_user.username }}
                {% else %} 
                    <a href="{% url 'app:profile' message.to_user.id %}">{{ message.from_user.username }}</a> 
                {% endif %}
            </h2>
            <h3>{{ message.send_date }}</h3>
          </div>
          <div class="message">
            {{ message.text }}
          </div>
        </li>
        
    </main>
  </div>
  
  
  

translationsite/app/templates/includes/unassigned_jobs.html
  <div class="card mt-5 w-75 mx-auto shadow p-3 mb-5 bg-white rounded">
    <div class="card-body ">
        <h4 class="card-title">{{ job.title }}</h4>
        <div class="card-subtitle mt-3"><b>Description:</b> {{ job.description }}</div>
        <div class="card-text mt-1"><b>Source language:</b>  {{ job.source_language }}</div>
        <div class="card-text mt-1"><b>Target language:</b>  {{ job.target_language }}</div>
        <div class="card-text mt-1"><b>Job field:</b>  {{ job.job_field }}</div>
        <p class="card-text mt-1"><b>Budget:</b>  {{ job.budget }} token(s)</p>
        <p class="card-text mt-1"><a href="{% url 'app:profile' job.user.id %}">User's profile</a></p>
        
        {% if user.userprofile.is_translator and user != job.user %}
        <div class="row">
           
            <form action="{% url 'app:jobs_bid' job.id %}" method="POST" class="col-2">
                {% csrf_token %}
                <button type="submit" class="btn custom-btn">Bid on Job</button>
            </form>
            <form action="{% url 'app:message_user' job.id %}" method="POST" class="col-2">
                {% csrf_token %}
                <button type="submit" class="btn custom-btn">Message User</a>
            </form>
            <div class="col-6"></div>
        </div>
        {% else %}
        <form action="{% url 'app:message_user' job.id %}" method="POST" class="col-2">
            {% csrf_token %}
            <button type="submit" class="btn custom-btn">Message User</a>
        </form>
        {% endif %}

    </div>
  </div>

translationsite/app/templates/includes/user_card.html
<div class="card mt-5 w-75 mx-auto shadow p-3 mb-5 bg-white rounded">
    <div class="card-body m-2 ">
      <h4 class="card-title">{{ user.user.username }}</h4>
      <div class="card-subtitle mb-2 text-muted">Email: {{ user.user.email }} </div>
      <div class="card-text"><a href="{% url 'app:profile' user.user.id %}">Show profile</a></div> 
    </div>
  </div>